# Test workflow for running a python script via github actions

name: Github actions update test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
#  schedule: 
#    - cron:  '* * * * *'

jobs: 
  run:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: run table updates
      run: |
        python update_repo_tables.py
    - name: Run spec updates
      run: |
        python updated_specs.py
    - name: Commit files
      id: commit_son
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions"
        git add --all
        git commit -m "update json data" -a
    - name: push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main 
